apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-service
data:
  DB_HOST: 127.0.0.1
  DB_PORT: 5433
  DB_USERNAME: myuser
  DB_NAME: mydatabase
---
apiVersion: v1
kind: Secret
metadata:
  name: postgrespass
type: Opaque
data:
  DB_PASSWORD: mypassword